### PR TITLE
Memory Management-Week8

### PR DESCRIPTION
**Pull request by LeshengJin**
1. conflicts in design/Memory-Management-conflicts.md
2. design in the last section of design/Memory-Management-design.md

### CODE REVIEW

**Comment by KamranAlipour** [comment]
Please take a look at the conflicts and see if you can resolve them, if any questions and doubt please share

**Comment by LeshengJin** [comment]
@KamranAlipour Done! Thanks!

**Comment by KamranAlipour** [comment]
Please double-check your PR by testing the interface. Make sure it can run smoothly and then try out some of your test programs in it. We tried it during the class and seems like we have wasm import issues..

**Comment by LeshengJin** [comment]
@KamranAlipour 
Now this pr passed most of testcases. And you can test it in the browser now. All failed testcases are related to set. `alloc/store/read` in `sets.wat` doesn't consider the header of the object. I believe there will be similar issues in other prs.
I have several concerns,
1. There are a lot of tmp variables, like `newObj`, `resultVal`. They will confuse the ref counting system. For example, we have `x.obj = obj1` in python, we will decrease the ref count of the old pointer in `x.obj` first, then increase the ref count of `obj1`. But if there is an additional stmt in the IR like `newVal = obj1`, the ref count of `obj1` will increase by 1 inadvertently. I walk around it in a simple way. The idea is if the var name contains any basename, like `resultVal1` includes `resultVal`, I would not generate increase/decrease ref count codes for this variable.
2. When we `store` some value, we need to know the value is a pointer or not. If it's a pointer, we can inc/dec the ref count of the value. And this type info is really help when we free the object in the memory. However, the tmp variables mentioned above do not have this type information in the `GlobalEnv`. For example, store `valname1` into the memory. It's OK for current pr, since we only count the reference, but don't free the 0-ref objects.
3. Why are we using `wasmint` in `store.value`? 
https://github.com/ucsd-cse231-s22/chocopy-wasm-compiler-B/blob/240b44c7c3285cab1e74924462a5e58e5518bfae/lower.ts#L685-L697

There is a more complete memory management implementation [here](https://github.com/LeshengJin/chocopy-wasm-compiler-B/tree/jls_pointer). If there are any questions about this pr or the complete implementation, please reach out.

**Comment by mb64** [comment]
@KamranAlipour All tests should pass now.  Like Lesheng said, the only failing test cases were related to sets.  We had originally thought it would be next to impossible to fix, since it was nearly 700 lines of mostly uncommented assembly that makes undocumented incorrect assumptions about memory layout, but we did somehow manage to fix it.

**Pull request closed without merging**
